### ISSUE TITLE
Rename openingScreen to openingMsg

### ISSUE THREAD

**Issue by jtespi** [SDev-2018/team-FE#1]
I propose we rename the JTextArea called openingScreen to openingMsg or openingMessage. The current name is too confusing as it seems to reference a panel, pane, or frame when it fact it is simply a text message. 
Also we should think about coloring this text or moving this feature and message into a pop-up window.

**Comment by Spaztech70** [comment]
Getting functionality to work is priority over refactoring. When you are the only one editing a class, if you want to rename something, just do it. The rest of us should be pulling before making edits anyway.

Thanks,

Sanford Johnston
800612154
720-569-3694


-------- Original message --------
